[versions]
agp = "8.0.2"
kotlin = "1.8.10"
core-ktx = "1.8.10"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
lifecycle-runtime-ktx = "2.6.1"
activity-compose = "1.7.2"
compose-bom = "2023.03.00"
hilt = "2.47"
hilt-navigation = "1.0.0"
accompanist = "0.30.1"

kotlinparcelize = "1.8.10"
coil = "2.4.0"
ui-util = "1.4.3"
navigation-compose = "2.6.0"
compose-material = "1.4.3"
retrofit = "2.9.0"
ggson = "2.10.1"
paging  = "3.1.1"
paging-compose  = "1.0.0-alpha19"
coroutines = "1.7.2"
animated-bar= "1.0.0"
room = "2.5.2"
appcompat = "1.6.1"
material = "1.9.0"
firebase = "32.3.1"
google = "4.3.15"
analytics = "17.5.0"

[libraries]
accompanist-navigationAnimation = { group = "com.google.accompanist", name = "accompanist-navigation-animation", version.ref = "accompanist" }

core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
material3 = { group = "androidx.compose.material3", name = "material3" }
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation", version.ref = "hilt-navigation" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
compose-material = { group = "androidx.compose.material", name = "material", version.ref = "compose-material" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
google-gson = { group = "com.google.code.gson", name = "gson", version.ref = "ggson" }
retrofit-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
paging = {group = "androidx.paging", name = "paging-runtime", version.ref = "paging"}
paging-compose = {group = "androidx.paging", name = "paging-compose", version.ref = "paging-compose"}
paging-ktx = {group = "androidx.paging", name = "paging-common-ktx", version.ref = "paging"}
animated-navigation-bar = {group = "com.exyte", name = "animated-navigation-bar", version.ref = "animated-bar"}
room-database-runtime = {group = "androidx.room", name = "room-runtime", version.ref = "room"}
room-database-compiler = {group = "androidx.room", name = "room-compiler", version.ref = "room"}
room-database-ktx = {group = "androidx.room", name = "room-ktx", version.ref = "room"}
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase"}
firebase-product = { group = "com.google.firebase", name = "firebase-analytics", version.ref = "analytics"}
firebase-auth = { group = "com.google.firebase", name = "firebase-auth-ktx"}
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx", version = "22.1.2" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinKapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
androidlibrary = { id = "com.android.library", version.ref = "agp" }
kotlinParcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlinparcelize" }
firebase = { id = "com.google.gms.google-services", version.ref = "google" }

[bundles]